celebrity = input("Celebrity: ")
pronoun = input("He or she: ")
noun = input("Noun: ")
vpt1 = input("Verb past tense: ")
celebrity2 = input("celebrity: ")
verb2 = input("Verb: ")
verb3 = input("Verb: ")
vpt = input("Verb past tense: ")
celebrity3 = input("Celebrity: ")
quote = input("Quote: ")
celebrity4 = input("Celebrity: ")
noun2 = input("Noun: ")
emotion = input("Emotion (noun form): ")
emotion2 = input("Emotion 2 (nound form): ")
emotion3 = input("Emotion 3 (nound form): ")
adjective = input("Adjective: ")
vpt2 = input("Verb past tense: ")
vpt3 = input("Verb past tense: ")
vpt4 = input("Verb past tense: ")
exclamation = input("Exclamation: ")
exclamation3 = input("Same Exclamation: ")
noun6 = input("Noun: ")


print("Thought I'd end up with " + celebrity)
print("But " + pronoun + " wasn't a " + noun)
print(vpt1 + " some songs about " + celebrity2)
print("Now I " + verb2 + " and " + verb3)
print("Even almost got " + vpt)
print("And for " + celebrity3 + " I'm so thankful")
print("Wish I could say, " + quote + " to " + celebrity4)
print("'Cause he was a/an " + noun2)
print("One taught me " + emotion)
print("One taught me " + emotion2)
print("And one taught me " + emotion3)
print("Now, I'm so " + adjective)
print("I've " + vpt2 + " and I've " + vpt3)
print("But that's not what I see")
print("So, look what I got")
print("Look what you " + vpt4 + " me")
print("And for that, I say")
print(exclamation + " , next")
print(exclamation + " , next")
print(exclamation + " , next")
print("I'm so fuckin' grateful for my " + noun6)
print(exclamation + " , next")
print(exclamation + " , next")
print(exclamation + " , next")
